version: "3.0"

services:
  app:
    restart: unless-stopped
    build: .
    environment:
      MYSQL_USER: "steve"
      MYSQL_PASSWORD: "changeme"
      MYSQL_DATABASE: "stevedb"
    volumes:
      - .:/code
    ports:
      - "8180:8180"
      - "8443:8443"

